/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actions */
        get: operations["list_actions_api_v2_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action */
        get: operations["get_action_api_v2_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/actions/{action_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Action */
        post: operations["retry_action_api_v2_actions__action_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v2_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_v2_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v2_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_v2_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Incident Chat */
        post: operations["incident_chat_api_v2_incidents__incident_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/reinvestigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reinvestigate Incident */
        post: operations["reinvestigate_incident_api_v2_incidents__incident_id__reinvestigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/suppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suppress Incident */
        post: operations["suppress_incident_api_v2_incidents__incident_id__suppress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/unsuppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsuppress Incident */
        post: operations["unsuppress_incident_api_v2_incidents__incident_id__unsuppress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/jenkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jenkins Workspace */
        get: operations["jenkins_workspace_api_v2_jenkins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/jenkins/builds/{build_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jenkins Build Detail */
        get: operations["jenkins_build_detail_api_v2_jenkins_builds__build_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/jenkins/builds/{build_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Jenkins Build */
        post: operations["analyze_jenkins_build_api_v2_jenkins_builds__build_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/jenkins/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jenkins Failures */
        get: operations["jenkins_failures_api_v2_jenkins_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v2_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_api_v2_scans_get"];
        put?: never;
        /** Enqueue Scan */
        post: operations["enqueue_scan_api_v2_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_v2_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Scan */
        post: operations["cancel_scan_api_v2_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Events */
        get: operations["scan_events_api_v2_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout */
        get: operations["logout_auth_logout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** V2ActionDetailResponse */
        V2ActionDetailResponse: {
            action: components["schemas"]["V2ActionResponse"];
            /** Attempts */
            attempts: components["schemas"]["V2DeliveryAttemptResponse"][];
        };
        /** V2ActionPage */
        V2ActionPage: {
            /** Items */
            items: components["schemas"]["V2ActionResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** V2ActionResponse */
        V2ActionResponse: {
            /** Action Type */
            action_type: string;
            /** Attempt Count */
            attempt_count: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Destination */
            destination: string;
            /** External Reference */
            external_reference: string | null;
            /** Failure Summary */
            failure_summary: string | null;
            /** Id */
            id: string;
            /** Incident Id */
            incident_id: string;
            /** Next Attempt At */
            next_attempt_at: string | null;
            /** Occurrence Id */
            occurrence_id: string;
            /** Rendered Payload */
            rendered_payload: {
                [key: string]: unknown;
            };
            /** Retry Cycle */
            retry_cycle: number;
            /** Status */
            status: string;
            /** Template Version */
            template_version: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** V2AnalysisDecisionResponse */
        V2AnalysisDecisionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Hash */
            evidence_hash: string;
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Outcome */
            outcome: string;
            /** Priority */
            priority: number;
            /** Reason */
            reason: string;
            /** Reason Code */
            reason_code: string;
            /** Request Id */
            request_id: string | null;
            /** Scan Id */
            scan_id: string | null;
            /** Source */
            source: string;
        };
        /** V2AnalyzeBuildRequest */
        V2AnalyzeBuildRequest: {
            /**
             * Mode
             * @default regular
             * @enum {string}
             */
            mode: "regular" | "deep";
        };
        /** V2CancelResponse */
        V2CancelResponse: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /** V2ChatRequest */
        V2ChatRequest: {
            /** History */
            history?: {
                [key: string]: string;
            }[];
            /** Incident Id */
            incident_id?: string | null;
            /** Message */
            message: string;
        };
        /** V2ChatResponse */
        V2ChatResponse: {
            /** As Of */
            as_of?: string | null;
            /** Content */
            content: string;
            /**
             * Coverage Status
             * @default unknown
             */
            coverage_status: string;
            /** References */
            references?: {
                [key: string]: string;
            }[];
        };
        /** V2CheckExecutionResponse */
        V2CheckExecutionResponse: {
            /** Categories */
            categories: string[];
            /** Completed At */
            completed_at: string | null;
            /** Failure Summary */
            failure_summary: string | null;
            /** Finding Count */
            finding_count: number;
            /** Name */
            name: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** V2DeliveryAttemptResponse */
        V2DeliveryAttemptResponse: {
            /** Attempt Number */
            attempt_number: number;
            /** Completed At */
            completed_at: string | null;
            /** Error Summary */
            error_summary: string | null;
            /** Id */
            id: string;
            /** Response Metadata */
            response_metadata: {
                [key: string]: unknown;
            };
            /** Retry Cycle */
            retry_cycle: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** V2FailurePatternResponse */
        V2FailurePatternResponse: {
            /** Affected Jobs */
            affected_jobs: string[];
            /** Classification */
            classification: string;
            /** Failed Wall Hours */
            failed_wall_hours: number;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Latest Build Id */
            latest_build_id: string;
            /** Occurrence Count */
            occurrence_count: number;
            /** Priority Score */
            priority_score: number;
            /** Signature */
            signature: string;
            /** Title */
            title: string;
        };
        /** V2IncidentDetailResponse */
        V2IncidentDetailResponse: {
            /** Actions */
            actions: components["schemas"]["V2ActionResponse"][];
            analysis_decision?: components["schemas"]["V2AnalysisDecisionResponse"] | null;
            /** Current Observations */
            current_observations?: components["schemas"]["V2ObservationResponse"][];
            incident: components["schemas"]["V2IncidentResponse"];
            investigation_request?: components["schemas"]["V2InvestigationRequestResponse"] | null;
            /** Jenkins Builds */
            jenkins_builds?: {
                [key: string]: unknown;
            }[];
            latest_investigation: components["schemas"]["V2InvestigationResponse"] | null;
            /** Observations */
            observations: components["schemas"]["V2ObservationResponse"][];
            /** Occurrences */
            occurrences: components["schemas"]["V2OccurrenceResponse"][];
        };
        /** V2IncidentPage */
        V2IncidentPage: {
            /** Items */
            items: components["schemas"]["V2IncidentResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** V2IncidentResponse */
        V2IncidentResponse: {
            /** Actionability */
            actionability: string | null;
            /**
             * Affected Resource Count
             * @default 0
             */
            affected_resource_count: number;
            /** Classification */
            classification: string | null;
            /** Correlation Key */
            correlation_key: string;
            /** Correlation Rule Id */
            correlation_rule_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Current Observation Count
             * @default 0
             */
            current_observation_count: number;
            /**
             * Domain
             * @default unknown
             */
            domain: string;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Id */
            id: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Occurrence Number */
            occurrence_number: number;
            /** Priority */
            priority: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Severity */
            severity: string;
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Suppressed At */
            suppressed_at: string | null;
            /** Suppressed By */
            suppressed_by: string | null;
            /** Suppressed Reason */
            suppressed_reason: string | null;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** V2InvestigationRequestResponse */
        V2InvestigationRequestResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Budget Kind */
            budget_kind: string;
            /** Build Id */
            build_id: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Summary */
            error_summary: string | null;
            /** Evidence Hash */
            evidence_hash: string;
            /** Id */
            id: string;
            /** Incident Id */
            incident_id: string;
            /** Investigation Id */
            investigation_id: string | null;
            /** Mode */
            mode: string;
            /** Next Attempt At */
            next_attempt_at: string | null;
            /** Occurrence Id */
            occurrence_id: string;
            /** Priority */
            priority: number;
            /** Requested By */
            requested_by: string | null;
            /** Reserved Tokens */
            reserved_tokens: number;
            /** Scan Id */
            scan_id: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** V2InvestigationResponse */
        V2InvestigationResponse: {
            /** Completed At */
            completed_at: string | null;
            /** Confidence */
            confidence: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Summary */
            error_summary: string | null;
            /** Evidence Hash */
            evidence_hash: string;
            /** Id */
            id: string;
            /** Input Version */
            input_version: string;
            /** Model */
            model: string;
            /** Model Calls */
            model_calls?: components["schemas"]["V2LLMCallResponse"][];
            /** Prompt Version */
            prompt_version: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Usage */
            usage: {
                [key: string]: unknown;
            };
        };
        /** V2JenkinsBuildDetailResponse */
        V2JenkinsBuildDetailResponse: {
            /** Build Number */
            build_number: number;
            /**
             * Building
             * @default false
             */
            building: boolean;
            /** Change Number */
            change_number?: string | null;
            /** Change Url */
            change_url?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Coverage
             * @default unknown
             */
            coverage: string;
            /** Downstream Builds */
            downstream_builds: {
                [key: string]: unknown;
            }[];
            /** Duration Ms */
            duration_ms: number;
            /**
             * Enrichment Status
             * @default pending
             */
            enrichment_status: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Failed Stage */
            failed_stage?: string | null;
            /**
             * Failure Classification
             * @default unknown
             */
            failure_classification: string;
            /**
             * Failure Signature
             * @default
             */
            failure_signature: string;
            /** Failure Summary */
            failure_summary?: string | null;
            /** Head Name */
            head_name?: string | null;
            /**
             * Head Type
             * @default unknown
             */
            head_type: string;
            /** Id */
            id: string;
            incident?: components["schemas"]["V2IncidentResponse"] | null;
            /** Incident Id */
            incident_id?: string | null;
            investigation_request?: components["schemas"]["V2InvestigationRequestResponse"] | null;
            /** Job Name */
            job_name: string;
            /**
             * Job Type
             * @default other
             */
            job_type: string;
            latest_investigation?: components["schemas"]["V2InvestigationResponse"] | null;
            /** Logical Run Key */
            logical_run_key: string;
            /**
             * Novelty
             * @default unclassified
             */
            novelty: string;
            /** Parent */
            parent?: string | null;
            /** Priority Reasons */
            priority_reasons?: string[];
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number;
            /**
             * Propagated Failure
             * @default false
             */
            propagated_failure: boolean;
            /**
             * Recovered
             * @default false
             */
            recovered: boolean;
            /** Repository */
            repository?: string | null;
            /** Result */
            result: string;
            /** Root Build Number */
            root_build_number: number;
            /** Root Job */
            root_job: string;
            /**
             * Source Allow Mr Comments
             * @default false
             */
            source_allow_mr_comments: boolean;
            /** Source Branch */
            source_branch?: string | null;
            /** Source Commit Sha */
            source_commit_sha?: string | null;
            /**
             * Source Kind
             * @default unresolved
             */
            source_kind: string;
            /** Source Profile Id */
            source_profile_id?: string | null;
            /**
             * Source Profile Registered
             * @default false
             */
            source_profile_registered: boolean;
            /** Source Provider */
            source_provider?: string | null;
            /** Source Reason */
            source_reason?: string | null;
            /**
             * Source Resolution Method
             * @default none
             */
            source_resolution_method: string;
            /** Source State */
            source_state?: string | null;
            /**
             * Source Status
             * @default pending
             */
            source_status: string;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Source Verified At */
            source_verified_at?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Trigger Kind
             * @default unknown
             */
            trigger_kind: string;
            /** Upstream Builds */
            upstream_builds: {
                [key: string]: unknown;
            }[];
            /** Url */
            url: string;
        };
        /** V2JenkinsBuildResponse */
        V2JenkinsBuildResponse: {
            /** Build Number */
            build_number: number;
            /**
             * Building
             * @default false
             */
            building: boolean;
            /** Change Number */
            change_number?: string | null;
            /** Change Url */
            change_url?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Coverage
             * @default unknown
             */
            coverage: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Enrichment Status
             * @default pending
             */
            enrichment_status: string;
            /** Failed Stage */
            failed_stage?: string | null;
            /**
             * Failure Classification
             * @default unknown
             */
            failure_classification: string;
            /**
             * Failure Signature
             * @default
             */
            failure_signature: string;
            /** Failure Summary */
            failure_summary?: string | null;
            /** Head Name */
            head_name?: string | null;
            /**
             * Head Type
             * @default unknown
             */
            head_type: string;
            /** Id */
            id: string;
            /** Incident Id */
            incident_id?: string | null;
            /** Job Name */
            job_name: string;
            /**
             * Job Type
             * @default other
             */
            job_type: string;
            /** Logical Run Key */
            logical_run_key: string;
            /**
             * Novelty
             * @default unclassified
             */
            novelty: string;
            /** Parent */
            parent?: string | null;
            /** Priority Reasons */
            priority_reasons?: string[];
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number;
            /**
             * Propagated Failure
             * @default false
             */
            propagated_failure: boolean;
            /**
             * Recovered
             * @default false
             */
            recovered: boolean;
            /** Repository */
            repository?: string | null;
            /** Result */
            result: string;
            /** Root Build Number */
            root_build_number: number;
            /** Root Job */
            root_job: string;
            /**
             * Source Allow Mr Comments
             * @default false
             */
            source_allow_mr_comments: boolean;
            /** Source Branch */
            source_branch?: string | null;
            /** Source Commit Sha */
            source_commit_sha?: string | null;
            /**
             * Source Kind
             * @default unresolved
             */
            source_kind: string;
            /** Source Profile Id */
            source_profile_id?: string | null;
            /**
             * Source Profile Registered
             * @default false
             */
            source_profile_registered: boolean;
            /** Source Provider */
            source_provider?: string | null;
            /** Source Reason */
            source_reason?: string | null;
            /**
             * Source Resolution Method
             * @default none
             */
            source_resolution_method: string;
            /** Source State */
            source_state?: string | null;
            /**
             * Source Status
             * @default pending
             */
            source_status: string;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Source Verified At */
            source_verified_at?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Trigger Kind
             * @default unknown
             */
            trigger_kind: string;
            /** Url */
            url: string;
        };
        /** V2JenkinsFailurePage */
        V2JenkinsFailurePage: {
            /** Items */
            items: components["schemas"]["V2JenkinsBuildResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total Count */
            total_count: number;
        };
        /** V2JenkinsWorkspaceResponse */
        V2JenkinsWorkspaceResponse: {
            /** Active Executions */
            active_executions: components["schemas"]["V2LogicalExecutionResponse"][];
            /** Busy Jobs */
            busy_jobs: components["schemas"]["V2JobFamilyResponse"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Multibranch */
            multibranch: components["schemas"]["V2MultibranchFamilyResponse"][];
            /** New Failures */
            new_failures: components["schemas"]["V2JenkinsBuildResponse"][];
            /** Recurring Patterns */
            recurring_patterns: components["schemas"]["V2FailurePatternResponse"][];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Window Hours */
            window_hours: number;
        };
        /** V2JobFamilyResponse */
        V2JobFamilyResponse: {
            /** Change Number */
            change_number?: string | null;
            /** Coverage */
            coverage: string;
            /** Failure Rate */
            failure_rate: number;
            /** Head Name */
            head_name?: string | null;
            /** Head Type */
            head_type: string;
            /** Job Name */
            job_name: string;
            /** Job Type */
            job_type: string;
            /**
             * Last Build At
             * Format: date-time
             */
            last_build_at: string;
            /** Latest Result */
            latest_result: string;
            /** Median Duration Minutes */
            median_duration_minutes: number;
            /** P95 Duration Minutes */
            p95_duration_minutes: number;
            /** Parent */
            parent?: string | null;
            /** Repository */
            repository?: string | null;
            /** Result Counts */
            result_counts: {
                [key: string]: number;
            };
            /** Run Count */
            run_count: number;
            /** Source Branch */
            source_branch?: string | null;
            /** Source Commit Sha */
            source_commit_sha?: string | null;
            /**
             * Source Kind
             * @default unresolved
             */
            source_kind: string;
            /** Source Profile Id */
            source_profile_id?: string | null;
            /**
             * Source Profile Registered
             * @default false
             */
            source_profile_registered: boolean;
            /** Source Provider */
            source_provider?: string | null;
            /** Source Reason */
            source_reason?: string | null;
            /**
             * Source Status
             * @default pending
             */
            source_status: string;
            /** Source Url */
            source_url?: string | null;
            /** Url */
            url: string;
            /** Wall Hours */
            wall_hours: number;
        };
        /** V2LLMCallResponse */
        V2LLMCallResponse: {
            /** Cache Creation Input Tokens */
            cache_creation_input_tokens: number;
            /** Cache Read Input Tokens */
            cache_read_input_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cost Source */
            cost_source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Estimated Cost Usd */
            estimated_cost_usd: number | null;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Purpose */
            purpose: string;
            /** Total Tokens */
            total_tokens: number;
        };
        /** V2LogicalExecutionResponse */
        V2LogicalExecutionResponse: {
            /** Affected Build Count */
            affected_build_count: number;
            /** Builds */
            builds: {
                [key: string]: unknown;
            }[];
            /** Change Number */
            change_number?: string | null;
            /** Change Url */
            change_url?: string | null;
            /** Classification */
            classification: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Logical Run Key */
            logical_run_key: string;
            /** Primary Build Id */
            primary_build_id: string;
            /** Priority Reasons */
            priority_reasons: string[];
            /** Priority Score */
            priority_score: number;
            /** Propagated Build Count */
            propagated_build_count: number;
            /** Repository */
            repository?: string | null;
            /** Root Build Number */
            root_build_number: number;
            /** Root Job */
            root_job: string;
            /** Source Branch */
            source_branch?: string | null;
            /** Source Commit Sha */
            source_commit_sha?: string | null;
            /**
             * Source Kind
             * @default unresolved
             */
            source_kind: string;
            /** Source Profile Id */
            source_profile_id?: string | null;
            /**
             * Source Profile Registered
             * @default false
             */
            source_profile_registered: boolean;
            /** Source Provider */
            source_provider?: string | null;
            /** Source Reason */
            source_reason?: string | null;
            /**
             * Source Resolution Method
             * @default none
             */
            source_resolution_method: string;
            /** Source State */
            source_state?: string | null;
            /**
             * Source Status
             * @default pending
             */
            source_status: string;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Source Verified At */
            source_verified_at?: string | null;
            /** Title */
            title: string;
        };
        /** V2MultibranchFamilyResponse */
        V2MultibranchFamilyResponse: {
            /** Active Child Count */
            active_child_count: number;
            /** Child Count */
            child_count: number;
            /** Children */
            children: {
                [key: string]: unknown;
            }[];
            /** Head Counts */
            head_counts: {
                [key: string]: number;
            };
            /** Parent */
            parent: string;
            /** Result Counts */
            result_counts: {
                [key: string]: number;
            };
            /** Run Count */
            run_count: number;
            /** Url */
            url: string;
        };
        /** V2ObservationResponse */
        V2ObservationResponse: {
            /** Category */
            category: string;
            /** Check Name */
            check_name: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Identity Dimensions */
            identity_dimensions: {
                [key: string]: unknown;
            };
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Resource Id */
            resource_id: string;
            /** Rule Id */
            rule_id: string;
            /** Scan Id */
            scan_id: string;
            /** Severity */
            severity: string;
            /** Stable Identity */
            stable_identity: string;
            /** Summary */
            summary: string;
        };
        /** V2OccurrenceResponse */
        V2OccurrenceResponse: {
            /** Id */
            id: string;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Number */
            number: number;
            /** Observation Identities */
            observation_identities: string[];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Responsible Checks */
            responsible_checks: string[];
        };
        /** V2OverviewResponse */
        V2OverviewResponse: {
            /** Active Incident Count */
            active_incident_count: number;
            /** Affected Resource Count */
            affected_resource_count: number;
            /** Coverage Status */
            coverage_status: string;
            /** Critical Incident Count */
            critical_incident_count: number;
            /** Environment */
            environment: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Jenkins */
            jenkins: {
                [key: string]: unknown;
            };
            /** Kubernetes */
            kubernetes: {
                [key: string]: unknown;
            };
            latest_scan: components["schemas"]["V2ScanResponse"] | null;
            /** Llm Usage */
            llm_usage?: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Top Incidents */
            top_incidents: components["schemas"]["V2IncidentResponse"][];
            /** Warning Incident Count */
            warning_incident_count: number;
        };
        /** V2ScanAnalysisItemResponse */
        V2ScanAnalysisItemResponse: {
            /** Completed At */
            completed_at?: string | null;
            /** Error Summary */
            error_summary?: string | null;
            /** Incident Id */
            incident_id: string;
            /** Incident Title */
            incident_title: string;
            /** Investigation Id */
            investigation_id?: string | null;
            /** Outcome */
            outcome: string;
            /** Reason */
            reason: string;
            /** Reason Code */
            reason_code: string;
            /** Request Id */
            request_id?: string | null;
            /** Request Status */
            request_status?: string | null;
            /** Severity */
            severity: string;
        };
        /** V2ScanAnalysisResponse */
        V2ScanAnalysisResponse: {
            /**
             * Active Count
             * @default 0
             */
            active_count: number;
            /**
             * Budget Deferred Count
             * @default 0
             */
            budget_deferred_count: number;
            /** Budget Limit Tokens */
            budget_limit_tokens?: number | null;
            /** Budget Limit Usd */
            budget_limit_usd?: number | null;
            /** Budget Metric */
            budget_metric?: string | null;
            /** Budget Projected Tokens */
            budget_projected_tokens?: number | null;
            /** Budget Projected Usd */
            budget_projected_usd?: number | null;
            /** Budget Reset At */
            budget_reset_at?: string | null;
            /** Budget Spent Tokens */
            budget_spent_tokens?: number | null;
            /** Budget Spent Usd */
            budget_spent_usd?: number | null;
            /**
             * Candidate Count
             * @default 0
             */
            candidate_count: number;
            /**
             * Deferred Count
             * @default 0
             */
            deferred_count: number;
            /**
             * Failed Count
             * @default 0
             */
            failed_count: number;
            /** Items */
            items?: components["schemas"]["V2ScanAnalysisItemResponse"][];
            /**
             * Manual Only Count
             * @default 0
             */
            manual_only_count: number;
            /**
             * Queued Count
             * @default 0
             */
            queued_count: number;
            /**
             * Reused Count
             * @default 0
             */
            reused_count: number;
            /**
             * Running Count
             * @default 0
             */
            running_count: number;
            /**
             * Selected Count
             * @default 0
             */
            selected_count: number;
            /**
             * Status
             * @default not_started
             * @enum {string}
             */
            status: "not_started" | "selecting" | "queued" | "running" | "complete" | "complete_with_issues" | "budget_deferred";
            /**
             * Succeeded Count
             * @default 0
             */
            succeeded_count: number;
        };
        /** V2ScanPage */
        V2ScanPage: {
            /** Items */
            items: components["schemas"]["V2ScanResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** V2ScanRequest */
        V2ScanRequest: {
            /** Categories */
            categories?: string[] | null;
            /**
             * Mode
             * @default regular
             * @enum {string}
             */
            mode: "regular" | "deep";
        };
        /** V2ScanResponse */
        V2ScanResponse: {
            analysis?: components["schemas"]["V2ScanAnalysisResponse"];
            /** Attempt Count */
            attempt_count: number;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            /** Categories */
            categories: string[];
            /** Checks */
            checks?: components["schemas"]["V2CheckExecutionResponse"][];
            /** Completed At */
            completed_at: string | null;
            /** Coverage Status */
            coverage_status?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Failure Summary */
            failure_summary: string | null;
            /** Id */
            id: string;
            /** Llm Usage */
            llm_usage?: {
                [key: string]: unknown;
            };
            /** Mode */
            mode: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Urls */
            urls: {
                [key: string]: string;
            };
        };
        /** V2SuppressionRequest */
        V2SuppressionRequest: {
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_actions_api_v2_actions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: ("pending" | "running" | "retry_scheduled" | "succeeded" | "permanently_failed") | null;
                action_type?: ("email" | "jira_create" | "jira_update" | "github_comment" | "gitlab_comment") | null;
                incident_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ActionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_api_v2_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ActionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_action_api_v2_actions__action_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v2_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v2_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v2_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: ("open" | "resolved" | "suppressed") | null;
                severity?: ("low" | "warning" | "critical") | null;
                source_type?: ("merge_request" | "repository" | "pipeline" | "multiple" | "infrastructure" | "unknown") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_api_v2_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_chat_api_v2_incidents__incident_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reinvestigate_incident_api_v2_incidents__incident_id__reinvestigate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2InvestigationRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suppress_incident_api_v2_incidents__incident_id__suppress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2SuppressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsuppress_incident_api_v2_incidents__incident_id__unsuppress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jenkins_workspace_api_v2_jenkins_get: {
        parameters: {
            query?: {
                window_hours?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2JenkinsWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jenkins_build_detail_api_v2_jenkins_builds__build_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2JenkinsBuildDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_jenkins_build_api_v2_jenkins_builds__build_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2AnalyzeBuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2InvestigationRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jenkins_failures_api_v2_jenkins_failures_get: {
        parameters: {
            query?: {
                window_hours?: number;
                view?: "all" | "new";
                result?: ("FAILURE" | "UNSTABLE" | "ABORTED") | null;
                job?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2JenkinsFailurePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v2_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2OverviewResponse"];
                };
            };
        };
    };
    list_scans_api_v2_scans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ScanPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_scan_api_v2_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_v2_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_v2_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_api_v2_scans__scan_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_auth_callback_get: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
