/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actions */
        get: operations["list_actions_api_v2_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action */
        get: operations["get_action_api_v2_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/actions/{action_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Action */
        post: operations["retry_action_api_v2_actions__action_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v2_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v2_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_v2_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Incident Chat */
        post: operations["incident_chat_api_v2_incidents__incident_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/reinvestigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reinvestigate Incident */
        post: operations["reinvestigate_incident_api_v2_incidents__incident_id__reinvestigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/suppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suppress Incident */
        post: operations["suppress_incident_api_v2_incidents__incident_id__suppress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/incidents/{incident_id}/unsuppress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsuppress Incident */
        post: operations["unsuppress_incident_api_v2_incidents__incident_id__unsuppress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_api_v2_scans_get"];
        put?: never;
        /** Enqueue Scan */
        post: operations["enqueue_scan_api_v2_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_v2_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Scan */
        post: operations["cancel_scan_api_v2_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Events */
        get: operations["scan_events_api_v2_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout */
        get: operations["logout_auth_logout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** V2ActionDetailResponse */
        V2ActionDetailResponse: {
            action: components["schemas"]["V2ActionResponse"];
            /** Attempts */
            attempts: components["schemas"]["V2DeliveryAttemptResponse"][];
        };
        /** V2ActionPage */
        V2ActionPage: {
            /** Items */
            items: components["schemas"]["V2ActionResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** V2ActionResponse */
        V2ActionResponse: {
            /** Action Type */
            action_type: string;
            /** Attempt Count */
            attempt_count: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Destination */
            destination: string;
            /** External Reference */
            external_reference: string | null;
            /** Failure Summary */
            failure_summary: string | null;
            /** Id */
            id: string;
            /** Incident Id */
            incident_id: string;
            /** Next Attempt At */
            next_attempt_at: string | null;
            /** Occurrence Id */
            occurrence_id: string;
            /** Rendered Payload */
            rendered_payload: {
                [key: string]: unknown;
            };
            /** Retry Cycle */
            retry_cycle: number;
            /** Status */
            status: string;
            /** Template Version */
            template_version: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** V2CancelResponse */
        V2CancelResponse: {
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /** V2ChatRequest */
        V2ChatRequest: {
            /** Incident Id */
            incident_id?: string | null;
            /** Message */
            message: string;
        };
        /** V2ChatResponse */
        V2ChatResponse: {
            /** Content */
            content: string;
        };
        /** V2DeliveryAttemptResponse */
        V2DeliveryAttemptResponse: {
            /** Attempt Number */
            attempt_number: number;
            /** Completed At */
            completed_at: string | null;
            /** Error Summary */
            error_summary: string | null;
            /** Id */
            id: string;
            /** Response Metadata */
            response_metadata: {
                [key: string]: unknown;
            };
            /** Retry Cycle */
            retry_cycle: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** V2IncidentDetailResponse */
        V2IncidentDetailResponse: {
            /** Actions */
            actions: components["schemas"]["V2ActionResponse"][];
            incident: components["schemas"]["V2IncidentResponse"];
            latest_investigation: components["schemas"]["V2InvestigationResponse"] | null;
            /** Observations */
            observations: components["schemas"]["V2ObservationResponse"][];
            /** Occurrences */
            occurrences: components["schemas"]["V2OccurrenceResponse"][];
        };
        /** V2IncidentPage */
        V2IncidentPage: {
            /** Items */
            items: components["schemas"]["V2IncidentResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** V2IncidentResponse */
        V2IncidentResponse: {
            /** Actionability */
            actionability: string | null;
            /** Classification */
            classification: string | null;
            /** Correlation Key */
            correlation_key: string;
            /** Correlation Rule Id */
            correlation_rule_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Occurrence Number */
            occurrence_number: number;
            /** Priority */
            priority: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Severity */
            severity: string;
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Suppressed At */
            suppressed_at: string | null;
            /** Suppressed By */
            suppressed_by: string | null;
            /** Suppressed Reason */
            suppressed_reason: string | null;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** V2InvestigationResponse */
        V2InvestigationResponse: {
            /** Completed At */
            completed_at: string | null;
            /** Confidence */
            confidence: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Summary */
            error_summary: string | null;
            /** Evidence Hash */
            evidence_hash: string;
            /** Id */
            id: string;
            /** Input Version */
            input_version: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Usage */
            usage: {
                [key: string]: unknown;
            };
        };
        /** V2ObservationResponse */
        V2ObservationResponse: {
            /** Category */
            category: string;
            /** Check Name */
            check_name: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Identity Dimensions */
            identity_dimensions: {
                [key: string]: unknown;
            };
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Resource Id */
            resource_id: string;
            /** Rule Id */
            rule_id: string;
            /** Scan Id */
            scan_id: string;
            /** Severity */
            severity: string;
            /** Stable Identity */
            stable_identity: string;
            /** Summary */
            summary: string;
        };
        /** V2OccurrenceResponse */
        V2OccurrenceResponse: {
            /** Id */
            id: string;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Number */
            number: number;
            /** Observation Identities */
            observation_identities: string[];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Responsible Checks */
            responsible_checks: string[];
        };
        /** V2ScanPage */
        V2ScanPage: {
            /** Items */
            items: components["schemas"]["V2ScanResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** V2ScanRequest */
        V2ScanRequest: {
            /** Categories */
            categories?: string[] | null;
            /**
             * Mode
             * @default regular
             * @enum {string}
             */
            mode: "regular" | "deep";
        };
        /** V2ScanResponse */
        V2ScanResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            /** Categories */
            categories: string[];
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Failure Summary */
            failure_summary: string | null;
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Urls */
            urls: {
                [key: string]: string;
            };
        };
        /** V2SuppressionRequest */
        V2SuppressionRequest: {
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_actions_api_v2_actions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: ("pending" | "running" | "retry_scheduled" | "succeeded" | "permanently_failed") | null;
                action_type?: ("email" | "jira_create" | "jira_update" | "github_comment" | "gitlab_comment") | null;
                incident_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ActionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_api_v2_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ActionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_action_api_v2_actions__action_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v2_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v2_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: ("open" | "resolved" | "suppressed") | null;
                severity?: ("low" | "warning" | "critical") | null;
                source_type?: ("merge_request" | "infrastructure" | "unknown") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_api_v2_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_chat_api_v2_incidents__incident_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reinvestigate_incident_api_v2_incidents__incident_id__reinvestigate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suppress_incident_api_v2_incidents__incident_id__suppress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2SuppressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsuppress_incident_api_v2_incidents__incident_id__unsuppress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2IncidentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_api_v2_scans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ScanPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_scan_api_v2_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["V2ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_v2_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_v2_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_api_v2_scans__scan_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_auth_callback_get: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
